kind = "web"
previewPath = "/"
title = "Zebvix Exchange"
version = "1.0.0"

[[services]]
localPort = 5000
name = "Flutter Web"
paths = ["/"]

[services.development]
run = "cd zebvix-flutter && flutter pub get && flutter run -d web-server --web-port=5000 --web-hostname=0.0.0.0"
